name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (5.7)
        uses: docker/build-push-action@v2
        with:
          context: 5.7
          push: true
          tags: src386/docker-pluxml:5.7
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push (5.8)
        uses: docker/build-push-action@v2
        with:
          context: 5.8
          push: true
          tags: 
            - src386/docker-pluxml:5.8
            - src386/docker-pluxml:latest
          platforms: linux/amd64,linux/arm64